info:
  config_name: v1
  template_name: test1.yaml
  template_path: E:\git_repos\phenopype\phenopype\templates\test1.yaml
  date_created: '20210216132548'
  date_last_modified:
steps: E:\git_repos\phenopype\phenopype\templates\test1.yaml
